// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var GenericRepository,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.Workshop || (window.Workshop = {});

  window.Workshop.GenericRepository = GenericRepository = (function() {
    function GenericRepository() {
      this.createListItems = __bind(this.createListItems, this);
    }

    GenericRepository.prototype.buildUrl = function(appendix) {
      return _spPageContextInfo.webAbsoluteUrl + appendix;
    };

    GenericRepository.prototype.getListItemType = function(listName) {
      return "SP.Data." + listName + "ListItem";
    };

    GenericRepository.prototype.createListItems = function(properties, listName) {
      var listItemType, params, payload;
      payload = properties;
      listItemType = this.getListItemType(listName);
      payload["__metadata"] = {
        "type": listItemType
      };
      return params = {
        url: requestUrl,
        type: 'POST',
        data: JSON.stringify(payload),
        headers: {
          "Accept": "application/json; odata=verbose",
          "content-type": "application/json; odata=verbose",
          "X-RequestDigest": $("#__REQUESTDIGEST").val()
        }
      };
    };

    return GenericRepository;

  })();

}).call(this);
